### ISSUE TITLE
installing magick on gha ubuntu

### ISSUE THREAD

**Issue by yonicd** [ropensci/magick#235]
i am trying to install `magick` on gha `ubuntu-16.04 (R 3.6)` and running into compiler issues, what would i need to change/add to get it to work? 

```r
##[error]Error: package or namespace load failed for ‘magick’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/runner/work/_temp/Library/magick/libs/magick.so':
  libMagick++-6.Q16.so.5: cannot open shared object file: No such file or directory
Execution halted
```

full github actions log: https://github.com/metrumresearchgroup/texPreview/runs/451731781?check_suite_focus=true#step:6:49

<details> <summary> gha yml </summary>

```yml
on:
  push

name: R-linux

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    if: "!contains(github.event.head_commit.message, 'skip linux')"
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-16.04, r: '3.6', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", args: "--no-manual" }
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
        
      - name: Install magick libs
        run: |
          sudo add-apt-repository ppa:cran/imagemagick
          sudo apt-get -qq update
          sudo apt-get -y install libmagick++-dev
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: install magick
        run: |
          install.packages('magick')
          library(magick)
          tiger <- image_read_svg('http://jeroen.github.io/images/tiger.svg', width = 350)
          tiger
        shell: Rscript {0}
```

**Comment by jeroen** [comment]
This happens due to the rstudio package manager. You probably need to remove the line with: `sudo add-apt-repository ppa:cran/imagemagick` because rstudio gives a package that was compiled without the ppa.

**Comment by yonicd** [comment]
works now. thanks!

https://github.com/metrumresearchgroup/texPreview/runs/452523489?check_suite_focus=true

**Comment by yonicd** [comment]
This seems to have reared it's head again using the script you helped out with in Feb

```yml
      - name: Install magick libs
        run: |
          sudo apt-get -qq update
          sudo apt-get -y install libmagick++-dev
```

https://github.com/metrumresearchgroup/texPreview/runs/665799365?check_suite_focus=true#step:11:23

**Comment by jeroen** [comment]
I think you may need to clear your cache. It's probably some old build.

**Comment by dmi3kno** [comment]
This again reminds me of failure to export an environment variable with location of shared libraries. `ldconfig` saved my life. https://stackoverflow.com/questions/50602024/error-while-loading-shared-libraries-libmagickcore-7-q16hdri-so-6

**Comment by yonicd** [comment]
still having a lot of trouble with this install. 

here is a very stripped down actions yml with no cache to test magick on linux. 

It doesnt work with r3.6 or r4.0.

https://github.com/yonicd/texPreview/runs/912597176?check_suite_focus=true

any help would be greatly appreciated.

thanks

```yml
on:
  push

name: R-linux

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: linux2
    if: "!contains(github.event.head_commit.message, 'skip linux2')"
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-16.04, r: '3.6', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest", args: "--no-manual" }
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
        
      - name: Install magick libs
        run: |
          sudo apt-get -qq update
          sudo apt-get -y install libmagick++-dev
          
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
          
      - name: install magick
        run: |
          install.packages(c('magick','rsvg'))
        shell: Rscript {0}

      - name: load magick
        run: |
          library(magick)
          tiger <- image_read_svg('http://jeroen.github.io/images/tiger.svg', width = 350)
          tiger
        shell: Rscript {0}

```
